stages:
  - build

variables:
  CACHE_FALLBACK_KEY: master

build:
  image: registry.gitlab.com/id5-sync/infrastructure/ci-image-node-google-chrome:id-7570-node-18.4-ci-docker-image
  stage: build
  script:
    - npm install --global gulp-cli
    - npm ci
    - npm run build:all
  artifacts:
    paths:
      - build/
  cache:
    paths:
      - "$CI_PROJECT_DIR/node_modules"
    key: $CI_COMMIT_REF_SLUG
