stages:
  - build

build:
  image: kekel87/node-chrome-firefox:1.5.0
  stage: build
  script:
    - npm install --global gulp-cli
    - npm ci
    - gulp build
  artifacts:
    paths:
      - build/dist/id5-api.js
      - build/dist/id5-api.js.map
      - build/dist/esp.js
      - build/dev/id5-api.js
      - build/dev/id5-api.js.map
      - build/dev/esp.js
