stages:
  - build

variables:
  CACHE_FALLBACK_KEY: master

build:
  image: registry.gitlab.com/id5-sync/infrastructure/ci-image-node-google-chrome:18.4.0-102.0.5005.61-1
  stage: build
  script:
    - npm install --global gulp-cli
    - npm ci
    - npm run build --workspaces
    - npm run build
  artifacts:
    paths:
      - build/
  cache:
    paths:
      - "$CI_PROJECT_DIR/node_modules"
    key: $CI_COMMIT_REF_SLUG
